version: '3'
networks:
  phpmyadmin:
    external: true
services:
  mysql:
    image: mysql:5
    restart: always
    environment:
      - PHPMYADMIN_SERVER=mysql_server1
      - MYSQL_ROOT_PASSWORD=root
    networks:
      phpmyadmin:
      default:
  mysql2:
    image: mysql:5
    restart: always
    environment:
      - PHPMYADMIN_SERVER=mysql_server2
      - MYSQL_ROOT_PASSWORD=root
    networks:
      phpmyadmin:
      default:
  mysql3:
    image: mysql:5
    restart: always
    environment:
      - PHPMYADMIN_SERVER=Mysql Server 3
      - MYSQL_ROOT_PASSWORD=root
    networks:
      phpmyadmin:
      default: